In [5]:
import numpy as np

In [10]:
a=[[[1,2],[3,4]],[[5,6],[7,8]]]

In [11]:
a_array = np.array(a)

In [12]:
a_array.shape

(2, 2, 2)

In [13]:
a_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a_array.ndim

3

In [16]:
print(a_array[0,1,0])

3


In [31]:
#inititalize array - bunch of ways to initialze it search on documentation
b_array = np.ones((2,3),dtype='int64')
b_array

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
c_ar = np.full((2,3),10)
c_ar

array([[10, 10, 10],
       [10, 10, 10]])

In [34]:
d_ar = np.random.rand(2,4)
print(d_ar)
type(d_ar) -- numpy.ndarray

[[0.19727824 0.25592526 0.28996835 0.2967094 ]
 [0.91978916 0.96639509 0.88484915 0.72534961]]


numpy.ndarray

In [37]:
b_array = np.ones((2,3),dtype='int64')
b_array
ar = b_array*2+2
print(ar)


[[4 4 4]
 [4 4 4]]


In [41]:
rand_arr = np.random.randint(1,11 ,size = (3,4))
print(rand_arr)

[[ 6  2  6  3]
 [ 5 10  4  9]
 [ 7  2  6  1]]


In [45]:
print(rand_arr.max())

10


In [47]:
print(rand_arr.mean(axis=1))

[4.25 7.   4.  ]


In [52]:
r2 = rand_arr.reshape(2,6)
print(r2)

[[ 4  8  5  9  9  3]
 [10  3  4 10  4  9]]


In [67]:
new_arr = np.random.randint(0,9, size = (2,4))
print(new_arr)
odd_nums = new_arr[new_arr%2!=0]
print(odd_nums)


[[1 3 5 6]
 [0 3 6 5]]
[1 3 5 3 5]


In [66]:
x = np.identity(3)
print(x)
y = np.identity(3)
z = print(x*y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [71]:
new_arr1 = np.random.randint(1,10 , size = (2,4))
print(new_arr)
print(new_arr1)
print("See Result")
new_arr2 = new_arr1*new_arr
print(new_arr2)

[[1 3 5 6]
 [0 3 6 5]]
[[4 6 7 5]
 [1 4 5 3]]
See Result
[[ 4 18 35 30]
 [ 0 12 30 15]]


In [72]:
print(new_arr2*2.54)

[[10.16 45.72 88.9  76.2 ]
 [ 0.   30.48 76.2  38.1 ]]
